### PR TITLE
Improve : Remove the requirement of equal with first dim of pretrain_dims and n_cluster

### PR DESCRIPTION
**Pull request by BlackPoint-CX**
1. Remove the requirement of equal with first dim of pretrain_dims and n_cluster.
User only need to define `n_clusters`. 
All other parameters has default values now.
2. Add the shape info output in `display_model_info`.
3. Change the `min_delta` to 0.0001 to get better extracted features.

### CODE REVIEW

**Review by Yancey0623 — COMMENTED** [review]
Can this PR fix the CI failed in SQLFlow: https://github.com/sql-machine-learning/sqlflow/issues/877 ?

**Review by Yancey0623 — DISMISSED** [review]
LGTM

**Comment by BlackPoint-CX** [comment]
> Can this PR fix the CI failed in SQLFlow: [sql-machine-learning/sqlflow#877](https://github.com/sql-machine-learning/sqlflow/issues/877) ?

I had tried several times and had not meet that problem again. 
This problem may be caused by gradient. 
I will keep an eye on that.

**Review by weiguoz — APPROVED** [review]
LGTM

**Pull request merged**
